### ISSUE TITLE
Chance for a revive? 

### ISSUE THREAD

**Issue by sternschnaube** [bendem/OreBroadcast#27]
Hello 😊
Seven years passed now, since you said you won't update this plugin.
Is there maybe any little chance for a different decision now?

It's one of the small plugins I've never forgot from the past, when I was running my Bukkit server.
Nowdays it's Fabric - but with projects like https://modrinth.com/mod/banner it should be possible to run it besides mods.
I would love to add it again to my server - it was super fun to see what your friends are finding.
Or challenging each other, who can find the bigger coal vein 😆

Support for the deepslate ore vartiants are missing, it would be great to have this.

**Comment by bendem** [comment]
The code is right here and the license is open. Anyone is free to take it and make it live a better live. It won't be me though.
